---
title: "Curriculum Vitae"
author: "Kyungho Jang"
# date: '2021-04-20T21:13:14-05:00'
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
subtitle: April 20, 2021
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```


***
**Office address**

Department of Social Studies Education  
Inha University  
100 Inha-ro, Michuhol-gu,  
Incheon 22212, KOREA  

Telephone: +82-32-860-7861  
Fax: +82-32-876-7859  
Email: [kjang@inha.ac.kr](mailto:kjang@inha.ac.kr)  
URL: [https://www.kjang.com](https://www.kjang.com)


***
**Education**

- Ph.D in Economics, The Ohio-State University, June 2002.

- M.A. in Economics, The Ohio State University, December 1998.

- M.A. in Economics, Chung-Ang University, Korea, August 1992.

- B.A. in Engineering of Electronics, Seoul National University, Korea, February 1989.


***
**Ph.D. Dissertation**

- Three Essays on Structural Vector Error Correction Models with Short-Run and Long-Run Restrictions.  
    Dissertation Supervisor: Masao Ogaki 


***
**Fellowship, Awards, and Honors**

- Best Teaching Awards, Inha Universtity, Spring 2009.

- Program for Enhancement of Graduate Studies Dissertation Fellowship, Department of Economics, The Ohio State University, Winter 2002.

- Program for Enhancement of Graduate Studies Dissertation Fellowship, Department of Economics, The Ohio State University, Summer 2001.

- The 2nd Place Award in the 15th Annual Edward F. Hayes Graduate Research Forum, The Ohio State University, 2001.

- The Ohio State University Alumni Research Award, The Ohio State University, 2000-2001.


***
**Financial Support**

- Inha University Research Grant, 2005-2016.

- Faculty Development Grant, The University of Alabama at Birmingham, 2004-2005.

- Faculty Development Grant, The University of Alabama at Birmingham, 2004-2005.

- Summer Research Grant, Department of Finance, Economics, and QM, The University of Alabama at Birmingham, Summer 2004.

- Summer Research Grant, Department of Finance, Economics, and QM, The University of Alabama at Birmingham, Summer 2003.

- Graduate Teaching Assistant, Department of Economics, The Ohio State University, January 1998 – June 2002.


***
**Research Interests**

- Money-Macroeconomics

- Time Series Econometrics

- Economics Education
 


***
**Professional Activities**

- Professor, Department of Social Studies Education, Inha University, September 2012 – present.

- Associate Professor, Department of Social Studies Education, Inha University, September 2007 – August 2012.

- Assistant Professor, Department of Social Studies Education, Inha University, March 2005 – August 2007.

- Assistant Professor, Department of Finance, Economics and Quantitative Methods, University of Alabama at Birmingham, August 2002 – January 2005.

- Graduate Teaching Assistant, Department of Economics, The Ohio State University, January 1998 – June 2002.

- Researcher, Korea Institute of Finance, Korea, April 1996 – July 1997.

- Researcher, Daewoo Research Institute, Korea, April 1994 – April 1996.

- Researcher, Tong-Yang Economic Research Institute, Korea, December 1991 – April 1994.


***
**Services**

- Editor-in-Chief, Korea Economic Education Association, March 2015 – present.

- Board of Editors, Association of Korean Economic Studies, March 2014 – present.

- Board of Directors, Korea Economic Education Association, March 2006 – present.

- Board of Directors, Association of Social Education in Korea, March 2007 – present.

- Dean, Admission Office, Inha University, March 2015 – February 2016.

- Vice Dean, Graduate School of Education, Inha University, August 2013 – February 2015.

- Board of Editors, Korea Economic Education Association, March 2006 – February 2015.

- Vice President, Korean Academy of Financial Consumers, March 2012 - February 2014.

- Board of Editors, Association of Social Education in Korea, March 2007 – February 2014.

- Member of Specialize Committee, Korean National Committee on ESD for UNESCO, September 2011 – August 2013.

- Board of Directors, Korean Academy of Financial Consumers, March 2010 - February 2012.

- Vice Dean, Admission Office, Inha University, August 2009 – July 2011.

- Secretary General, Korea Economic Education Association, March 2007 – February 2011.

- Chair, Department of Social Studies Education, Inha University, March 2007 – February 2009.


***
**Teaching Experience**

- Understanding Principles of Economics at Inha University: 2005 – present.

- Lectures on Economics, A Graduate Course at Inha University: 2005 – present.

- Studies on Method of Economic Education, A Graduate Course at Inha University: 2005 – present.

- Economy and Society at Inha University: 2005 – present.

- Principles of Citizen Education and Market Economy at Inha University: 2005 – present.

- Business Honors Research Method at The University of Alabama, Birmingham: Spring 2005.

- Econometrics at The University of Alabama, Birmingham: Spring 2004.

- Principles of Business Statistics at The University of Alabama, Birmingham: Spring 2003, Autumn 2003, Spring 2004, Autumn 2004.

- Principles of Macroeconomics at The University of Alabama, Birmingham: Fall 2002, Spring 2003, Autumn 2003, Spring 2004.

- Survey of Econometrics at The University of Alabama, Birmingham: Spring 2004.

- Econometrics, A Graduate Course, Teaching Assistant at The Ohio State University: Spring 2001, Autumn 2001.

- Macroeconometrics, A Graduate Course, Guest Lecturer and Teaching Assistant at The Ohio State University: Spring 2001, Autumn 2001.

- Principles of Macroeconomics, Instructor with full responsibility at The Ohio State University: Winter 2001, Autumn 2000, Summer 2000.

- Principles of Macroeconomics, Teaching Assistant at The Ohio State University: Spring 2000, Autumn 1999.

- Principles of Microeconomics, Teaching Assistant at The Ohio State University: Winter 2000.


***
**Publications**

- “Comparison of Financial Literacy between Korean and U.S. High School Students,” with Jinsoo Hahn and Hyung Joon Park, *International Review of Economics Education*, 16 (Part A), 22–38, May 2014.

- “International Comparison of the Economic Knowledge from the Result of the Test of Economic Knowledge 2 in Korea,” with Kyungmo Kim, *Korean Journal of Economic Education*, 20 (2), 109–133, August 2013.

- “Alternative Maximum Likelihood Estimation of Structural Vector Autoregressive Models Partially Identified with Short-Run Restrictions,” *Journal of Money, Credit and Banking*, 45 (2-3), 465–476, March–April 2013.

- “The Effects of a Translation Bias on the Scores for the Basic Economics Test,” with Jinsoo Hahn, *Journal of Economic Education*, 43 (2), 133–148, April 2012.

- “Economic Education in Korea Current Status and Changes,” with Jinsoo Hahn, *Journal of Economic Education*, 41 (4), 436–447, December 2010.

- “A Study on the Korea Economic Accreditation Test,” with Sungrae Moon and Kyungmo Kim, *(Japanese) Journal of Economic Education*, 29, 24–37, September 2010.

- “A Structural Vector Error Correction Model with Short-Run and Long-Run Restrictions,” *Korean Economic Review*, 24 (1), 199–232, June 2008.

- “Impulse Response Analysis with Long Run Restrictions on Error Correction Models,” *Korea Review of Applied Economics*, 8 (3), 97–126, December 2006.

- “An Alternative Approach to Estimation of Structural Vector Error Correction Models with Long-Run Restrictions,” *Economics Letters*, 90 (1), 126–131, January 2006.

- “The Effects of Monetary Policy Shocks on Exchange Rates: A Structural Vector Error Correction Model Approach,” with Masao Ogaki, *Journal of the Japanese and International Economies*, 18 (1), 99–114, March 2004.

- “The Effects of Japanese Monetary Policy Shocks on Exchange Rates: A Structural Vector Error Correction Model Approach,” with Masao Ogaki, *Monetary and Economic Studies*, 21(1), 1–34, February 2003.


***
**Publications in Korean**

- “An Analysis of the Contents of National Accounts in Economics Textbooks,” *Korean Journal of Economic Education*, 23 (3), 55–83, December 2016.

- “Analysis of the Time Intervals in 119 Ambulance Services,” with Kyunghee Kang, Yoonhee Jang and Kyungdong Hah, *Fire Science and Engineering*, 30 (4), 128–134, August 2016.

- “Study of Korean Symptom Expression in 119 Emergency Calls,” with Yoonhee Jang, Kyunghee Kang and Kyeonghae Kim, *Fire Science and Engineering*, 30 (4), 135–140, August 2016.

- “An Analysis of Contents in the Chinese High School Thought and Politics (1) - Economic Life Textbook Focusing on the Number of Economic Concepts and the Types of Inquiry Activities ,” with Hyewon Shin, *Theory and Research in Citizenship Education*, 48 (2), 57–89, June 2016.

- “Gender Difference in Economics Knowledge Understanding,” with Seon Hye Song and Kyungdong Hahn, *Korean Journal of Economic Education*, 22 (3), 123–140, December 2015.

- “The Effects of Ambiguity on the Willingness-To-Pay, the Willingness-To-Accept and their Gaps,” with Jongchurl Kim, *Korean Journal of Economic Education*, 22 (1), 73–98, April 2015.

- “An Analysis on the Contents of Finance Chapter in High School ‘Economics’ Textbooks,” with Hyewon Shin, *Theory and Research in Citizenship Education*, 46 (4), 1–29, December 2014.

- “The Meaning of Opportunity Cost for Consumer’s Rational Choice,” with Jongchurl Kim, *Korean Journal of Economic Education*, 21 (1), 1–24, April 2014.

- “An Analysis of Economic Education Contents in Teachers Colleges of Korea,” with Hyung Joon Park and Kyungdong Hahn, *Korean Journal of Economic Education*, 20 (3), 1–36, December 2013.

- “An Analysis of Regional Differences Regarding Club Participation Rates of General High Schools,” with Hyewon Shin and Jongchurl Kim, *Journal of Education & Culture*, 19 (3), 33–52, December 2013.

- “The Effects of University Admission Process on Private Education,” with Hye-Won Shin, *Theory and Research in Citizenship Education*, 45 (1), 27–41, March 2013.

- “An Analysis of Correlations between the Difficulties of Test and its Selection of Economics Subjects at College Scholastic Ability Test,” with Yun Ho Chung and Kyungdong Hahn, *Journal of Korean Economic Studies*, 30 (3), 47–71, September 2012.

- “An Analysis on the Characteristics of Students Who Select Economics for College Scholastic Ability Test,” with Kyungdong Hahn, *Korean Journal of Economic Education*, 18 (2), 45–57, December 2011.

- “An Analysis on the Effects of Online Private Lectures and EBS Lectures on the Scores of the Social Studies Inquiry Subject of the College Scholastic Ability Test,” with Hye-Won Shin, *Theory and Research in Citizenship Education*, 43 (3), 55–73, September 2011.

- “Opportunity Cost and Rational Choice,” *Korean Journal of Economic Education*, 18 (1), 1–21, June 2011.

- “The Effects of Highschool Selection on the Achievement and Interest on Social Studies,” with Hye-Won Shin, *Theory and Research in Citizenship Education*, 42 (4), 55–77, December 2010.

- “A Study on the Economic Attitudes for Highschool Students - Focusing on Applicants to Student Economic Proficiency Contest,” with Kyungdong Hahn, *Korean Journal of Economic Education*, 17 (1), 49–69, June 2010.

- “An Analysis on the Scopes and Sequences of Economic Education in the Social Studies Curriculum in Texas and California States,” with Eunyoung Kang, *Theory and Research in Citizenship Education*, 42 (1), 127–150, March 2010.

- “The Effects of Identity on Economic Attitudes for Highschool Students,” *Korean Journal of Economic Education*, 16 (2), 67–89, December 2009.

- “The Effects of Social Studies Teachers Background on their Attitudes to Economic Education,” with Kyungdong Hahn and Kyungmo Kim, *Theory and Research in Citizenship Education*, 40 (4), 21-41, December 2008.

- “Policy Effectiveness Analysis and Selection Bias: Focusing on a Sequential Selection Model of The Government Small Business Loan Program,” with Sukwon Lee, Junki Kim, Youngbum Lee and Minho Lee, *Korean Public Administration Review*, 42 (1), 197-227, Spring 2008.

- “Effectiveness Analysis of The Government Small Business Loan Program: Comparing the Types of Loan Program Management,” with Junki Kim, Youngbum Lee, Sukwon Lee and Minho Lee, *Korean Journal of Public Administration*, 46 (1), 1-32, March 2008.

- “A Study of Specialization and Efficiency on the Production Possibilities Frontier,” *Korean Journal of Economic Education*, 14 (2), 221-236, December 2007.

- “A Study on the Productivity Effects of Venture Business Start-up Program,” with Junki Kim, Sukwon Lee, Youngbum Lee, Kichul Shin and Minho Lee, *Productivity Review*, 21 (3), 153-183, September 2007.

- “An Analysis of the Inquiry Activities of Economics Textbooks in the 7th Social Studies Curriculum,” with Euisook Ham, *Korean Journal of Economic Education*, 13 (2), 19-47, December 2006.

- “An Analysis of ‘Knowledge’ and ‘Skill’ Factors in Elementary Social Education Textbooks - Focused on the Number of Economic Concepts,” *Korean Journal of Economic Education*, 13 (2), 1-18, December 2006.

- “An Analysis of Participation in Lifelong Education in Korea - Focusing on the Semi-aged more than Fifty Years Old,” with Mi-Jung Lee, *Inha Educational Research*, 12, 75–108, December 2006.


***
**Books**

- “Comparative Korean Results of TUCE with U.S. and Japan,” with Kyungdong Hahn and Kyungmo Kim, in *Comparative Studies on Economic Education in Asia-Pacific Region*, edited by Michael W. Watts, Tadayoshi Asano, William B. Walstad, and Shintaro Abe, 53–77, Shumpusa Publishing, February 2010.


***
**Books in Korean**

- *Economics* (an official textbook for high school), with Hyeong Joon Park, Seok Min Jeong, Kyungmo Kim, Kyungdong Hahn and Jinsoo Hahn, Chunjae Education, March 2014.

- *Economics* (an official textbook for high school), with Hyeong Joon Park, Jinsoo Hahn, Seok Min Jeong, Kyungmo Kim and Kyungdong Hahn, Chunjae Education, March 2012.

- *Economics – Teaher’s Manual*, with Hyeong Joon Park, Jinsoo Hahn, Seok Min Jeong, Kyungmo Kim and Kyungdong Hahn, Chunjae Education, March 2012.

- *KERI 2010 Korea’s Quarterly Macroeconomic Model*, with Gyeong Lyeob Cho and Chang Bae Kim, Korea Economic Research Institute, July 2011.


***
**Working Papers**

- “The Effects of Monetary Policy Shocks on Exchange Rates: A Structural Vector Error Correction Model Approach,” with Masao Ogaki, Working Paper, No. 01-02, Department of Economics, Ohio State University, March 2001. (Published in Journal of Japanese and International Economies, 18 (1), 99–114, March 2004.)

- “Impulse Response Analysis with Long Run Restrictions on Error Correction Models,” Working Paper, No. 01-04, Department of Economics, Ohio State University, January 2001. (Published in Korea Review of Applied Economics, 8 (3), 97–126, December 2006.)


***
**Completed Papers**

- “Comparison of Financial Literacy Between Korean and U.S. High School Students,” with Jinsoo Hahn and Hyung Joon Park, manuscript, submitted to International Review of Economic Education, November 2013.

- “The Effects of the Understanding of Opportunity Cost on Consumer Choice,” with Jongchurl Kim, manuscript, submitted to Korean Journal of Economic Education, November 2013.

- “An Analysis of Regional Differences in Club Participation Rates - Focusing on General High Schools,” with Hyewon Shin and Jongchurl Kim, manuscript, submitted to Journal of Education and Culture, November 2013.


***
**Work in Progress**

- Structural Macroeconometrics, with Masao Ogaki, a graduate textbook, A book proposal submitted to Cambridge University Press (revise-and-resubmit requested).

- “Confidence Intervals on Structural Vector Error Correction Models Partially Identified with Long-Run Restrictions,” Manuscript, October 2004.

- “Asymptotic Properties of Impulse Responses and Forecast-Error Variance Decompositions in Structural Vector Autoregressive Models Partially Identified with Long-Run Restrictions,” Manuscript, September 2004.

- “International Business Cycle: Generalized Two-Step Maximum Likelihood Estimation and Asymptotic Properties of Impulse Responses and Forecast-Error Variance Decompositions,” Manuscript, December 2003.

- “An IS-LM Model: Generalized Two-Step Maximum Likelihood Estimation and Asymptotic Properties of Impulse Responses and Forecast-Error Variance Decompositions,” Manuscript, September 2003.

- “Measuring Monetary Policy: A Structural Vector Autoregressive Model Partially Identified with Short-run and Long-run Restrictions,” Manuscript, September 2003.

- “Generalized Two-Step Maximum Likelihood Estimation of Structural Vector Error Correction Models Partially Identified with Short-Run and Long-Run Restrictions (I),” Manuscript, May 2004.

- “Generalized Two-Step Maximum Likelihood Estimation of Structural Vector Error Correction Models Partially Identified with Short-Run and Long-Run Restrictions (II),” Manuscript, August 2004.


***
**Conference Presentations**

- “The Effects of Ambiguity on the Willingness-To-Pay, the Willingness-To-Accept and its Gap,” 2015 Economics Joint Conference at Yonsei University in Korea, Korea Economic Education Association and Korean Economic Association, February 2015.

- “An Analysis on the Contents of Finance Chapter in High School ‘Economics’ Textbooks,” 2014 Summer Conference at Jeju National University, Korea Economic Education Association, August 2014.

- “A Structural Analysis of Financial Literacy,” 2014 Annual Conference at Gyeongsang National University, Korean Association of Social Education, July 2014.

- “The Effects of the Understanding of Opportunity Cost on Consumer Choice,” 2014 Economics Joint Conference at Sungkyunkwan University in Korea, Korea Economic Education Association and Korean Economic Association, February 2014.

- “Financial Literacy of Korean High School Students,” AEA 2014 Annual Meeting at Philadelphia, American Economic Association, January 2014.

- “The Common and Country-Specific Factors of Financial Literacy Between Korea and the U.S. High School Students,” 2013 Annual Conference at Inha University, Korean Association of Social Education, August 2013.

- “An Analysis of Economic Education Contents in Teachers Colleges of Korea,” 2013 Summer Conference at Seowon University, Korea Economic Education Association, August 2013.

- “Comparison of Financial Literacy Between Korean and the U.S. High School Students,” 2013 Summer Conference at Chungnam National University, Korean Academy of Financial Consumers, August 2013.

- “An Analysis of the Regional Differences of Highschool Students’ Club Participation,” 2013 Annual Conference at Korea National University of Education, Korean Educational Research Association, June 2013.

- “The Common and Country–Specific Factors of Financial Literacy Between Korea and the U.S. High School Students,” Conference on Teaching & Research on Economic Education at Chicago, Illinois, AEA Committee on Economic Education, May 2013.

- “An Analysis of Correlations between the Difficulties of Test and its Selection among Social Studies Subjects at College Scholastic Ability Test,” 2012 Economics Joint Conference at Yonsei University in Korea, Korea Economic Education Association and Korean Economic Association, February 2012.

- “Do Low Scores Mean Less Knowledge? - The Effects of a Translation Bias on the Scores for the Basic Economics Test,” 2011 National Conference on Teaching Economics at Stanford University, Committee on Economic Education, June 2011.

- “An Analysis on the Characteristics of Students Who Select Economics for College Scholastic Ability Test,” 2011 Economics Joint Conference at Chung-Ang University in Korea, Korea Economic Education Association and Korean Economic Association, February 2011.

- “International Comparison of the Economic Knowledge from the Result of the Test of Economic Knowledge 2 in Korea,” 2010 Annual Conference at Tachibana University in Kyoto, Japan Society of Economic Education, September 2010.

- “An Analysis on the Effects of Highschool Selection on the Achievement and Interest on Social Studies,” 2010 Summer Conference at Gongju National University of Education in Korea, Korea Economic Education Association, August 2010.

- “The Effects of Highschool Selection on the Achievement and Interest on Social Studies,” 2010 Annual Conference at Gyeongin National University of Education in Korea, Association of Social Education in Korea, August 2010.

- “A Study on the Korea Economic Accreditation Test,” 2010 Annual Conference at Gyeongin National University of Education in Korea, Association of Social Education in Korea, August 2010.

- “An Analysis on the Scopes and Sequences of Economic Education in the Social Studies Curriculum in Texas and California States,” 2010 Economics Joint Conference at Seoul National University in Korea, Korea Economic Education Association and Korean Economic Association, February 2010.

- “A Study on the Korea Economics Accreditation Test,” 2009 Annual Conference at Kansai University in Osaka, Japan Society of Economic Education, September 2009.

- “The Effects of Identity on Economic Attitudes for Highschool Students,” 2009 Summer Conference at Sunchon National University in Korea, Korea Economic Education Association, August 2009.

- “An Analytical Comparison of Knowledge of Economics,” An International Conference on Economic Education at Waseda University in Tokyo, Research Group of Economic Education & Institute of Asia-Pacific Studies, August 2009.

- “A Review of Economic Education in Korea,” An International Conference on Economic Education at Waseda University in Tokyo, Research Group of Economic Education & Institute of Asia-Pacific Studies, August 2009.

- “Economic Education in Korea: The Status and Changes,” 2009 International Economic Education Symposium at San Francisco, National Council on Economic Education, January 2009.

- “The Revised National Curriculum and the Revision of Teacher Training System,” 45th Workshop at Dorim Highschool in Korea, Incheon Social Studies Association, December 2008.

- “The Korea Economics Accreditation Test,” Conference at Korea Federation of Banks Building, Korea Development Institute, December 2008.

- “The Effects of Social Studies Teachers Background on their Attitudes to Economic Education,” International Conference for the 30th Anniversary at Soon Chun Hyang University, Korea Economic Education Association, November 2008.

- “Results of the Test of Understanding College Economics for Korean College Students,” NCEE 2008 Annual Conference at Biloxy, National Council on Economic Education, October 2008.

- “The Effects of Social Studies Teachers Background on their Attitudes to Economic Education,” 2008 Annual Conference at Pusan National University, Association of Social Education in Korea, July 2008.

- “A Study on the Opportunity Cost,” 2007 Summer Conference at Daegu National University of Education, Korea Economic Education Association, August 2007.

- “Generalized Two-Step Maximum Likelihood Estimation of Structural Vector Autoregressive Models partially identified with Short-Run Restrictions,” 2007 Economics Joint International Conference at Seoul National University in Korea, Korean Econometric Society and Korean Economic Association, February 2007.

- “Generalized Two-Step Maximum Likelihood Estimation of Structural Vector Autoregressive Models partially identified with Short-Run Restrictions,” The 16 th Annual Meeting of the Midwest Econometrics Group, October 2006.

- “Generalized Two-Step Maximum Likelihood Estimation of Structural Vector Autoregressive Models Partially Identified with Short-Run Restrictions,” Far Eastern Meeting of the Econometric Society, July 2004.

- “Asymptotic Properties of Impulse Responses and Forecast-Error Variance Decompositions,” The 12th Annual Meeting of the Midwest Econometrics Group, October 2002.

- “A Structural Vector Error Correction Model with Short-Run and Long-Run Restrictions,” The 11th Annual Meeting of the Midwest Econometrics Group, October 2001.

- “Impulse Response Analysis with Long Run Restrictions on Error Correction Models,” Far Eastern Meeting of the Econometric Society, July 2001.

- “The Effects of Monetary Policy Shocks on Exchange Rates: A Structural Vector Error Correction Model Approach,” North American Summer Meeting of the Econometric Society, June 2001.


***
**Workshop Presentations**

- Macroeconomics Workshop, Department of Economics, The Ohio State University, October 2001.

- 15th Annual Edward F. Hayes Graduate Research Forum, Ohio State University, April 2001.

- Money and Macroeconomics Seminar, Department of Economics, Ohio State University, April 2001.

- Macroeconomics Workshop, Department of Economics, Ohio State University, November 2000.

- Macroeconomics Workshop, Department of Economics, Ohio State University, May 2000.


***
**Computer Software**

- “User Guide for VECM with Long-Run Restrictions,” with Masao Ogaki, Manuscript, May 2001.

- “User Guide for GMM,” with Masao Ogaki, Manuscript, April 2001.

- “User Guide for CCR,” with Masao Ogaki, Manuscript, April 2001.

- “User Guide for Johansen’s Method,” with Masao Ogaki, Manuscript, April 2001.


***
**Referee**

- *Econometric Theory*; *International Economic Journal*; *Journal of Forecasting*; *Journal of Business and Economic Statistics*; *Journal of Money, Credit, and Banking*; *Quarterly Review of Economics and Finance*.

- *Journal of Korean Economy*; *Journal of the Korean Urban Geographical Society*; *Korean Journal of Economic Education*; *Secondary Education Research*; *The Korean Economic Review*; *Theory and Research in Citizenship Education.*
 